version: "3.7"

services:
  e2e:
    image: dasigr/cypress-base:latest
    volumes:
      - ./cypress.json:/app/cypress.json
      - ./cypress:/app/cypress
    environment:
      CYPRESS_PROJECT_ID: ${CYPRESS_PROJECT_ID}
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
      CYPRESS_BASE_URL: ${CYPRESS_BASE_URL}
    command: npm run e2e:record -- --parallel --ci-build-id ${BITBUCKET_BUILD_NUMBER}
